# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/research/mass-SAMCON-sfu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/research/mass-SAMCON-sfu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/research/mass-SAMCON-sfu/CMakeFiles /home/kevin/research/mass-SAMCON-sfu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/research/mass-SAMCON-sfu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mass.out

# Build rule for target.
mass.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mass.out
.PHONY : mass.out

# fast build rule for target.
mass.out/fast:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/build
.PHONY : mass.out/fast

# target to build an object file
BVHData.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/BVHData.o
.PHONY : BVHData.o

# target to preprocess a source file
BVHData.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/BVHData.i
.PHONY : BVHData.i

# target to generate assembly for a file
BVHData.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/BVHData.s
.PHONY : BVHData.s

# target to build an object file
MyWindow.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/MyWindow.o
.PHONY : MyWindow.o

# target to preprocess a source file
MyWindow.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/MyWindow.i
.PHONY : MyWindow.i

# target to generate assembly for a file
MyWindow.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/MyWindow.s
.PHONY : MyWindow.s

# target to build an object file
config_loader.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/config_loader.o
.PHONY : config_loader.o

# target to preprocess a source file
config_loader.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/config_loader.i
.PHONY : config_loader.i

# target to generate assembly for a file
config_loader.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/config_loader.s
.PHONY : config_loader.s

# target to build an object file
mass.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/mass.o
.PHONY : mass.o

# target to preprocess a source file
mass.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/mass.i
.PHONY : mass.i

# target to generate assembly for a file
mass.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/mass.s
.PHONY : mass.s

# target to build an object file
refine.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/refine.o
.PHONY : refine.o

# target to preprocess a source file
refine.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/refine.i
.PHONY : refine.i

# target to generate assembly for a file
refine.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/refine.s
.PHONY : refine.s

# target to build an object file
sample.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/sample.o
.PHONY : sample.o

# target to preprocess a source file
sample.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/sample.i
.PHONY : sample.i

# target to generate assembly for a file
sample.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/sample.s
.PHONY : sample.s

# target to build an object file
setup_frag.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/setup_frag.o
.PHONY : setup_frag.o

# target to preprocess a source file
setup_frag.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/setup_frag.i
.PHONY : setup_frag.i

# target to generate assembly for a file
setup_frag.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/setup_frag.s
.PHONY : setup_frag.s

# target to build an object file
simulator.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/simulator.o
.PHONY : simulator.o

# target to preprocess a source file
simulator.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/simulator.i
.PHONY : simulator.i

# target to generate assembly for a file
simulator.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/simulator.s
.PHONY : simulator.s

# target to build an object file
utility.o:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/utility.o
.PHONY : utility.o

# target to preprocess a source file
utility.i:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/utility.i
.PHONY : utility.i

# target to generate assembly for a file
utility.s:
	$(MAKE) -f CMakeFiles/mass.out.dir/build.make CMakeFiles/mass.out.dir/utility.s
.PHONY : utility.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mass.out"
	@echo "... edit_cache"
	@echo "... BVHData.o"
	@echo "... BVHData.i"
	@echo "... BVHData.s"
	@echo "... MyWindow.o"
	@echo "... MyWindow.i"
	@echo "... MyWindow.s"
	@echo "... config_loader.o"
	@echo "... config_loader.i"
	@echo "... config_loader.s"
	@echo "... mass.o"
	@echo "... mass.i"
	@echo "... mass.s"
	@echo "... refine.o"
	@echo "... refine.i"
	@echo "... refine.s"
	@echo "... sample.o"
	@echo "... sample.i"
	@echo "... sample.s"
	@echo "... setup_frag.o"
	@echo "... setup_frag.i"
	@echo "... setup_frag.s"
	@echo "... simulator.o"
	@echo "... simulator.i"
	@echo "... simulator.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

